import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    width: 20,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 1,
    color: '#111',
    
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#111',
    marginBottom: 20,
  },
  pictureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 20,
  },
  pictureBox: {
    width: 72,
    height: 72,
    borderRadius: 14,
    backgroundColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  pictureImage: {
    width: '100%',
    height: '100%',
  },
  addPictureText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1D9E75',
    textDecorationLine: 'underline',
    letterSpacing: 0.3,
  },
  nameInput: {
    borderWidth: 1.5,
    borderColor: '#111',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 15,
    color: '#111',
  },
  divider: {
    height: 1,
    backgroundColor: colors.surface,
    marginVertical: 28,
  },
  maxSizeInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  maxSizeLabel: {
    fontSize: 14,
    color: '#666',
  },
  maxSizeInput: {
    width: 60,
    borderWidth: 1,
    borderColor: colors.borderWhite,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: '#111',
    textAlign: 'center',
  },
  footer: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: 12,
  },
  createButton: {
    backgroundColor: '#061414',
    paddingVertical: 18,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom:20
  },
  createButtonDisabled: {
    backgroundColor: '#E5E5E5',
  },
  createText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 1,
  },
  createTextDisabled: {
    color: '#aaa',
  },
  emptyMembersText: {
    fontSize: 13,
    color: '#999',
    marginBottom: 8,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  memberAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111',
  },
  adminBadge: {
    backgroundColor: '#111',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginLeft: 'auto',
  },
  adminBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  dateBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#111',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  dateLabel: {
    fontSize: 11,
    color: '#999',
  },
  dateValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111',
  },
  clearDatesText: {
    fontSize: 12,
    color: '#D85A30',
    marginBottom: 14,
  },
  inviteCodeBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: '#111',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: 4,
    marginBottom: 10,
  },
  rankingHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rankingToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#111',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  rankingToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
  },
  inviteCodeText: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 3,
    color: '#111',
  },
  shareInviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#111',
    borderRadius: 14,
    paddingVertical: 12,
  },
  shareInviteButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#111',
    letterSpacing: 0.5,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: '#D85A30',
    paddingVertical: 14,
    borderRadius: 999,
    marginBottom: 12,
  },
  deleteButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#D85A30',
    letterSpacing: 0.5,
  },
});