import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    backgroundColor: colors.background,
    gap: 8,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textPrimary,
    marginLeft: 2,
  },
  pillsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.backgroundAlt,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
  },
  pillText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  startButton: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 50,
    backgroundColor: colors.backgroundDark,
    paddingVertical: 18,
    borderRadius: 30,
    alignItems: 'center',
  },
  startText: {
    color: colors.textOnDark,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 1,
  },
  buttonRow: {
  position: 'absolute',
  left: 16,
  right: 16,
  bottom: 54,
  flexDirection: 'row',
  gap: 12,
},
pauseButton: {
  flex: 1,
  backgroundColor: colors.backgroundDark,
  paddingVertical: 18,
  borderRadius: 30,
  alignItems: 'center',
  borderWidth: 1.5,
  borderColor: colors.borderBlack,
},
pauseButtonText: {
  fontSize: 14,
  fontWeight: '700',
  color: colors.textOnDark,
  letterSpacing: 1,
},
finalizeButton: {
  flex: 1.4,
  backgroundColor: '#BCFF00',
  paddingVertical: 18,
  borderRadius: 30,
  alignItems: 'center',
},
finalizeButtonText: {
  fontSize: 14,
  fontWeight: '700',
  color: colors.textOnAccent,
  letterSpacing: 1,
},
selectedRouteBanner: {
  position: 'absolute',
  top: 118,
  left: 16,
  right: 16,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  backgroundColor: colors.backgroundAlt,
  borderRadius: 20,
  paddingVertical: 8,
  paddingHorizontal: 14,
},
selectedRouteText: {
  fontSize: 13,
  fontWeight: '600',
  color: colors.textPrimary,
  flexShrink: 1,
},
});