import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#061414',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    backgroundColor: '#061414',
  },
  headerStats: {
    flexDirection: 'row',
    gap: 16,
  },
  statInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statInlineText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  floatingRow: {
    position: 'absolute',
    top: 120,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  routesPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  routesPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
  },
  rightButtons: {
    gap: 10,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locateButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#061414',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startDrawingPill: {
    position: 'absolute',
    marginTop:180,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#0B1F12',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  startDrawingText: {
    color: '#BCFF00',
    fontSize: 12,
    fontWeight: '700',
  },
  bottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 32,
  },
  toolsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  toolsLeft: {
    flexDirection: 'row',
    gap: 8,
  },
  toolButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F1EFE8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  territoriesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  territoriesLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111',
  },
  toggle: {
    width: 40,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ccc',
    padding: 2,
    justifyContent: 'center',
  },
  toggleOn: {
    backgroundColor: '#BCFF00',
  },
  toggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
  },
  toggleThumbOn: {
    transform: [{ translateX: 16 }],
  },
  drawButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#061414',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  drawButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
  },
  freeUsesText: {
    textAlign: 'center',
    fontSize: 12,
    color: '#999',
    marginBottom: 16,
  },
  saveButton: {
    backgroundColor: '#BCFF00',
    paddingVertical: 16,
    borderRadius: 28,
    alignItems: 'center',
    marginBottom:20
  },
  saveButtonDisabled: {
    backgroundColor: '#EDEDED',
  },
  saveText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#061414',
    letterSpacing: 0.5,
  },
  saveTextDisabled: {
    color: '#aaa',
  },
});