import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    gap: 8,
    backgroundColor: '#fff',
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  tabsScroll: {
    flex: 1,
  },
  tabsScrollContent: {
    gap: 8,
  },
  tabPill: {
    backgroundColor: '#F1EFE8',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  tabPillActive: {
    backgroundColor: '#BCFF00',
  },
  tabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#333',
  },
  tabTextActive: {
    color: '#061414',
  },
  activityDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#F1EFE8',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 20,
  },
  activityDropdownText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
  },
  levelCard: {
    backgroundColor: '#0B2A1E',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
  },
  levelCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  levelLabel: {
    fontSize: 13,
    fontWeight: '800',
    fontStyle: 'italic',
    color: '#BCFF00',
    letterSpacing: 1,
  },
  levelValue: {
    fontSize: 56,
    fontWeight: '800',
    color: '#fff',
    lineHeight: 58,
  },
  levelStatsRight: {
    gap: 14,
  },
  levelStatRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  levelStatTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  levelStatValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  levelStatSub: {
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
  },
  expBarTrack: {
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(188, 255, 0, 0.15)',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  expBarFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(188, 255, 0, 0.4)',
    borderRadius: 11,
  },
  expBarText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'right',
    paddingRight: 12,
  },
  whiteSection: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -16,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
    marginTop: 8,
  },
  seasonPill: {
    backgroundColor: '#061414',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  seasonPillText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#BCFF00',
    letterSpacing: 0.3,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#111',
  },
  sectionSubtitle: {
    fontSize: 13,
    color: '#888',
    marginBottom: 16,
  },
  sectionSubtitleLast: {
    fontSize: 13,
    color: '#888',
    marginBottom: 16,
    marginTop: -12,
  },
  challengesRow: {
    gap: 12,
    paddingBottom: 8,
  },
  challengeCard: {
    width: 150,
    backgroundColor: '#0B2A1E',
    borderRadius: 18,
    padding: 14,
    alignItems: 'center',
  },
  claimBadge: {
    backgroundColor: '#BCFF00',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 14,
  },
  claimBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#061414',
  },
  challengeIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  challengeTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 14,
  },
  progressBox: {
    width: '100%',
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(188, 255, 0, 0.15)',
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#BCFF00',
    borderRadius: 3,
  },
  progressText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#BCFF00',
  },
  claimButton: {
    backgroundColor: 'rgba(188, 255, 0, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
  },
  claimButtonText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#BCFF00',
  },
  competitionsRow: {
    gap: 10,
    paddingBottom: 4,
  },
  competitionAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#0B2A1E',
  },
  competitionAvatarImage: {
    width: '100%',
    height: '100%',
  },
});