import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: { flexDirection: 'row', alignItems: 'center' },
  backText: { fontSize: 15, fontWeight: '700', color: colors.textPrimary, marginLeft: 2 },
  content: { flex: 1, paddingHorizontal: 24, paddingTop: 28 },
  checkCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.richBlack,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 16,
  },
  titleGreen: {
    fontSize: 32,
    fontWeight: '800',
    fontStyle: 'italic',
    color: colors.laurelLeaf,
    textAlign: 'center',
    textTransform: 'uppercase',
    lineHeight: 34,
  },
  titleBlack: {
    fontSize: 32,
    fontWeight: '800',
    fontStyle: 'italic',
    color: colors.textPrimary,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: 16,
    lineHeight: 34,
  },
  subtitle: {
    fontSize: 15,
    color: colors.secondary,
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: 24,
  },
  divider: { height: 1, backgroundColor: colors.border, marginBottom: 24 },
  sectionTitle: { fontSize: 20, fontWeight: '800', color: colors.textPrimary, marginBottom: 6 },
  sectionDescription: { fontSize: 13, color: colors.textMuted, marginBottom: 14 },
  sectionSpacing: { height: 28 },
  card: {
    backgroundColor: colors.background,
    borderRadius: 18,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  code: { fontSize: 26, fontWeight: '800', color: colors.textPrimary, letterSpacing: 1, flexShrink: 1 },
  link: { fontSize: 14, fontWeight: '600', color: colors.textPrimary, flex: 1 },
  actionButton: {
    backgroundColor: colors.backgroundAlt,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 4,
  },
  actionButtonText: { fontSize: 12, fontWeight: '700', color: colors.textPrimary },
  footer: { paddingHorizontal: 24, paddingBottom: 28, paddingTop: 12 },
  goButton: { backgroundColor: colors.richBlack, paddingVertical: 18, borderRadius: 999, alignItems: 'center' },
  goButtonText: { fontSize: 14, fontWeight: '700', color: colors.ceilingWhite, letterSpacing: 1 },
});